# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-11 17:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0006_adoption_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='adoption',
            name='canceled_by_adopter',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='adoption',
            name='canceled_by_owner',
            field=models.BooleanField(default=False),
        ),
    ]
