# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-07 16:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='animal_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='animals', to='animals.AnimalType'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='adopter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adopters', to=settings.AUTH_USER_MODEL),
        ),
    ]
