# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-09 16:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0002_auto_20171007_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animaltype',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
